export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  JOIN_US: '/joinus',
  BUSINESS_APPLICATION: '/business-application',
  LOGIN: '/login',
  REGISTER: '/register',
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  SUPER_ADMIN_DASHBOARD: '/admin/super-dashboard',
  APPLICATION_MANAGEMENT: '/admin/application-management',
  BUSINESS_MANAGEMENT: '/admin/business-management',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_MENU_MANAGEMENT: '/admin/menu-management',
  ADMIN_RESERVATION_RULES: '/admin/reservation-rules',
  ADMIN_BUSINESS_SETTINGS: '/admin/business-settings',
  ADMIN_BLOCKED_USERS: '/admin/blocked-users',
};

export const ROUTE_NAMES = {
  HOME: 'Ana Sayfa',
  ABOUT: 'Hakkımızda',
  CONTACT: 'İletişim',
  JOIN_US: 'Bize Katıl',
  BUSINESS_APPLICATION: 'İşletme Başvurusu',
  LOGIN: 'İşletme Girişi',
  REGISTER: 'Kayıt Ol',
  ADMIN: 'Super Admin Girişi',
  ADMIN_LOGIN: 'Admin Giriş',
  SUPER_ADMIN_DASHBOARD: 'Super Admin Paneli',
  APPLICATION_MANAGEMENT: 'Başvuru Yönetimi',
  BUSINESS_MANAGEMENT: 'İşletme Yönetimi',
  ADMIN_DASHBOARD: 'Kontrol Paneli',
  ADMIN_TABLE_PLAN: 'Masa Planı',
  ADMIN_MENU_MANAGEMENT: 'Menü Yönetimi',
  ADMIN_RESERVATION_RULES: 'Rezervasyon Kuralları',
  ADMIN_BUSINESS_SETTINGS: 'İşletme Ayarları',
  ADMIN_BLOCKED_USERS: 'Engellenen Kullanıcılar',
};
